### ISSUE TITLE
[Bug]: cant sign up Something wrong happened while signing up / in: user-existed

### ISSUE THREAD

**Issue by Shadowheg** [remotely-save/remotely-save#1037]
### What happened?

![Image](https://github.com/user-attachments/assets/b34a60a9-fd5e-4e04-9101-6514c4519eec)
after try to sign up on website https://remotelysave.com/ with NEW clear email i see message: "Something wrong happened while signing up / in: user-existed"

### What OS are you using?

Windows

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

others

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by jorge882** [comment]
Same problem for me.  I'm on Linux (Ubuntu), and I can't login in either Firefox or Chrome.  Every time I try to login, I receive the same error: "Something wrong happened while signing up / in: user-existed"

**Comment by BlueMighty** [comment]
I have the same problem sincèrement yesterday when my Obsidian sync stopped working with the message "... JASON", so I disconnected my account and now I can sign in. I got à message saying "Internal Server Issue"

![Image](https://github.com/user-attachments/assets/0aca5190-fdaa-4f6d-b814-b5352127f7b2)

**Comment by princept** [comment]
I have the same problem "Internal Server Error"

1. Tried using different web browsers: Sometimes, errors can occur due to cache or setting issues specific to a particular browser. I attempted to log in to https://remotelysave.com/user/signupin using different web browsers (such as Chrome, Edge, and Firefox).
2. Cleared browser cache and cookies: I cleared the cache and cookies of the browser I was using and then tried logging in again.
3. Used Incognito/Private Browsing mode: To rule out potential interference from browser extensions, I attempted to log in using the browser's Incognito (or Private Browsing) mode.
4. Deleted the .obsidian/plugins/remotely-save folder and reinstalled the plugin: I deleted the plugin's folder located at .obsidian/plugins/remotely-save and then reinstalled the Remotely Save plugin.
5. Deleted related items found in third-party apps(https://myaccount.google.com/): I also searched for and deleted items related to 'remotely' in various third-party applications, but the symptoms remained the same.

Unfortunately, even after trying all of that, the symptoms are still the same.

## My info ##
Os ver : windows11
Google Drive ver: 107.0.3.0
RemoteIy Save Version: 0.525
Obsidian Current version: v1.8.10

![Image](https://github.com/user-attachments/assets/bc1f5597-6854-4ecc-a50c-2c8506272179)

**Comment by sturan53** [comment]
I have same issue i can't sign up i try everything mentioned above

**Comment by nathang21** [comment]
I've tried multiple emails, I either get `Something wrong happened while signing up: user-existed` or `Something wrong happened while signing up / in: password-mismatched` errors. I'm interested in the Pro Merge feature.

**Comment by elianpullen** [comment]
Also having the same issue, tried with Mullvad browser, Firefox, Firefox incognito and multiple emails and everytime the same error: 'Something wrong happened while signing up / in: user-existed'

**Comment by joekaiser** [comment]
Same issue for me. both in the app (Linux, Mac, and Andorid) and on the web

**Comment by iz0eyj** [comment]
Same, Android

**Comment by tnytxt** [comment]
same. PC browsers

**Comment by MMALI3287** [comment]
Same here on Windows 11 Brave browser

**Comment by Monteth** [comment]
It seems like this repo has been abandoned, as there are no signs of life from the creator @fyears (except the automatic commits). It is possible that the web auth server is no longer maintained, so it caused the pro features to be bricked...

**Comment by joekaiser** [comment]
Agree, it looks to be abandoned. I was already thinking of forking it, maybe I should....

**Comment by Monteth** [comment]
> Agree, it looks to be abandoned. I was already thinking of forking it, maybe I should....

Notice the `pro` folder has a different licence than the rest of the repo, and we are not allowed to modify its content... It would be nice to get rid of it completely, and add GDrive and other functionalities to the core, so it wont use the auth anymore.

**Comment by joekaiser** [comment]
> > Agree, it looks to be abandoned. I was already thinking of forking it, maybe I should....
> 
> Notice the `pro` folder has a different licence than the rest of the repo, and we are not allowed to modify its content... It would be nice to get rid of it completely, and add GDrive and other functionalities to the core, so it wont use the auth anymore.

I saw that 👍

**Comment by fyears** [comment]
hi all the website sign in problems have been resolved. please try again . thanks for the report and sorry for the inconvenience!

@jorge882 @iz0eyj @joekaiser @princept @nathang21 @Monteth @elianpullen @MMALI3287 @BlueMighty

**Comment by fyears** [comment]
> It seems like this repo has been abandoned, as there are no signs of life from the creator @fyears (except the automatic commits). It is possible that the web auth server is no longer maintained, so it caused the pro features to be bricked...

hi @Monteth i am still alive but busy earning a life... sorry for the no responses for a while. i will try to pick up remotely save at least for serious bugs like this. thank you for your understanding!

**Comment by fyears** [comment]
> Agree, it looks to be abandoned. I was already thinking of forking it, maybe I should....

hi sorry but actually pro folder is not allowed to modify. now the website sign in problems have been fixed so please try again. thank you for your understanding

**Comment by fyears** [comment]
> It seems like this repo has been abandoned, as there are no signs of life from the creator @fyears (except the automatic commits). It is possible that the web auth server is no longer maintained, so it caused the pro features to be bricked...

@Monteth actually the server is located on cloudflare and it reaches some limitations in free plan because of too many users. 

i have to pay to upgrade the plan... 

so yes i am still willing to support the product and maintain (personally pay for!) the server. 

please give me some time. :-(

**Comment by joekaiser** [comment]
That's totally ok and understandable! Thanks for letting us know what happened. 

Happy to donate some $$ for support if you have a way

**Comment by nathang21** [comment]
@fyears can you please add a way to reset password? I'm still getting this error every time I try and sign up with any of the emails i've tried previously.

<img width="1173" alt="Image" src="https://github.com/user-attachments/assets/b63a5023-51e9-400f-9492-d04cdc0dc5eb" />

**Comment by fyears** [comment]
@nathang21 

hi

1. please send me an email to remotelysave@gmail.com using your email
2. then i will delete your account. but don't worry! read ahead
3. and you can register a new account using the same email and your new password. enable your desired features.
4. and please set up the auth progress on your obsidian remotely save plugin again. actually the account is fully new so everything has to go through again.


right now the pro feature is completely free so register again doesn't hurt anything or your wallet.

after the "real payment" feature be implemented, a real password reset method will be implemented too.

thank you for your understanding and support!

**Comment by Monteth** [comment]
@fyears I get it, but please understand that the signing functionality doesn't bring any benefit to users. Instead, it adds cost for you and acts as a blocker for them. Maybe it's time to choose a direction—either open it completely or introduce pricing to make it profitable.

**Comment by fyears** [comment]
> @fyears I get it, but please understand that the signing functionality doesn't bring any benefit to users. Instead, it adds cost for you and acts as a blocker for them. Maybe it's time to choose a direction—either open it completely or introduce pricing to make it profitable.

completely agree with you. i am considering this issue seriously.
