### ISSUE TITLE
[Bug]: Sync Fail on Android

### ISSUE THREAD

**Issue by UbioZur** [remotely-save/remotely-save#108]
### What happened?

I have setup the sync and synced some files from the desktop 
(FEDORA Flathub flatpack obsidian 0.14.6, remotely-save 0.3.24).

I am trying to now sync to a new install on Android (Android 12), same vault name.
S3 connection work, but the sync fail while generating plan.
x = undefined is not a valid size.

Android 12

[FIXED](https://github.com/remotely-save/remotely-save/issues/108#issuecomment-1120400445): by disabling the config file sync. CORS may have helped too.

![Screenshot_20220506-194206](https://user-images.githubusercontent.com/13650202/167118360-12cf2c38-29ee-435f-a1b3-a0c86ab1296b.png)

### What OS are you using?

Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.24

### Version of Obsidian

1.2.0

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by UbioZur** [comment]
> Have you set the CORS headers?

I haven't touch it at all. and looking through the doc, I don't believe I should
https://github.com/remotely-save/remotely-save#s3

> If you are using Obsidian desktop >= 0.13.25 or mobile >= 1.1.1, you can skip this CORS part.

I use desktop 0.14.6 (above 0.13.25) and mobile 1.2.0 (above 1.1.1)

**Comment by UbioZur** [comment]
Found to access the debug log, in case it helps:

```
[2022-05-07T12:54:34+09:00] remotely-save-1651895674827: start sync, triggerSource=auto
[2022-05-07T12:54:37+09:00] ERROR! MESSAGE: x=undefined is not a valid size, STACK: Error: x=undefined is not a valid size
    at Me (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:293719)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:211:305559)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:280525)
    at new Promise (<anonymous>)
    at a (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:280270)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:211:304584)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:211:306944)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:280525)
[2022-05-07T12:54:42+09:00] remotely-save-1651895682016: start sync, triggerSource=manual
[2022-05-07T12:54:44+09:00] remotely-save-1651895684804: abort sync, triggerSource=manual, error while generating_plan
[2022-05-07T12:54:44+09:00] ERROR! MESSAGE: x=undefined is not a valid size, STACK: Error: x=undefined is not a valid size
    at Me (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:293719)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:211:305559)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:280525)
    at new Promise (<anonymous>)
    at a (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:280270)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:211:304584)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:211:306944)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (http://localhost/app.js:1:1444808), <anonymous>:177:280525)
[2022-05-07T12:55:18+09:00] mkdir _debug_remotely_save
```

**Comment by fyears** [comment]
I am sorry, but a few days before I found out that that there is some bugs in Android Obsidian old version that was fixed in insider build 1.2.1. (iPhone Obsidian 1.1.1 indeed works. Latest desktop version also works) The doc hasn’t been updated to reflect this info.

So since you are using Android Obsidian 1.2.0, may be you could try to add cors config to the service provider and try again.

**Comment by UbioZur** [comment]
> I am sorry, but a few days before I found out that there was a bug in Android Obsidian old version, that was later fixed in insider build 1.2.1 by Obsidian team (iPhone Obsidian 1.1.1 indeed works. Latest desktop version also works.) The doc hasn’t been updated to reflect this info.
> 
> So since you are using Android Obsidian 1.2.0, may be you could try to add cors config to the service provider and try again.

I have added the CORS, or I think I did, I can't find a way test if the CORS have been added, That was my first touch with s3 cli, and my bucket is not public (obviously) so all the curl methods I found don't really works!

The APP still show the error, so i would like to make sure the CORS are properly setup.
I have used those CORS: https://github.com/remotely-save/remotely-save/issues/71

Also I am using a contabo S3, not AWS S3, but it uses/allow awscli (which is what I used).

**Comment by fyears** [comment]
According to your report, you have successfully synced the file on desktop.

To verify the cors have been working or not, on your **desktop Obsidian**, turn **off** the following remotely save setting (bypass cors locally) and try to sync again. You should be able to see this setting on desktop, but not on Android. If the next sync of desktop still works, it means that the cors has been set successfully.

![2CBD458B-8D06-47B7-BA28-2FE5E6ED9696](https://user-images.githubusercontent.com/1142836/167251767-65a7c90d-ab7e-437f-a679-0006294a3dd9.png)

**Comment by UbioZur** [comment]
> According to your report, you have successfully synced the file on desktop.

I did indeed

> To verify the cors has been working or not, on your **desktop Obsidian**, turn **off** the following remotely save setting (bypass cors locally) and try to sync again. You should be able to see this setting on desktop, but not on Android. If the next sync of desktop still works, it means that the cors has been set successfully.

I disabled it, restarted Obsidian, and the sync still works on the desktop. So the problems does not comes from the CORS.

Any ideas on what to try before waiting for the 1.2.1 release?

**Comment by fyears** [comment]
Would you like to follow the instructions here? Thank you so much!

1. Manually download and extra `my-dist.zip` from [here](https://github.com/remotely-save/remotely-save/actions/runs/2286518936), and install the `main.js` into your Android Obsidian (Copy it to your `<vault>/.obsidian/plugins/remotely-save/`). It's a special debug mode "release" printing extra info.
2. Then follow [this](https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/check_console_output.md) to check the console output of the Android, to see if there  is any hint about what stops the sync progress.

**Comment by UbioZur** [comment]
Here is the log file:

```
VM59:177 remotely-save-1652007529605: start sync, triggerSource=manual
VM59:177 inside ensembleMixedStates
VM59:177 remoteStates: [
  {
    "key": ".obsidian/plugins/remotely-save/data.json",
    "existRemote": true,
    "mtimeRemote": 1651923695434,
    "mtimeRemoteFmt": "2022-05-07T20:41:35+09:00",
    "sizeRemoteEnc": 1904,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/plugins/obsidian-kanban/manifest.json",
    "existRemote": true,
    "mtimeRemote": 1651827766135,
    "mtimeRemoteFmt": "2022-05-06T18:02:46+09:00",
    "sizeRemoteEnc": 320,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": "Home.md",
    "existRemote": true,
    "mtimeRemote": 1651923316295,
    "mtimeRemoteFmt": "2022-05-07T20:35:16+09:00",
    "sizeRemoteEnc": 32,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/core-plugins.json",
    "existRemote": true,
    "mtimeRemote": 1651923665991,
    "mtimeRemoteFmt": "2022-05-07T20:41:05+09:00",
    "sizeRemoteEnc": 240,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/page-preview.json",
    "existRemote": true,
    "mtimeRemote": 1651830644390,
    "mtimeRemoteFmt": "2022-05-06T18:50:44+09:00",
    "sizeRemoteEnc": 48,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": "Stratus - Server/Traefik.md",
    "existRemote": true,
    "mtimeRemote": 1651831364591,
    "mtimeRemoteFmt": "2022-05-06T19:02:44+09:00",
    "sizeRemoteEnc": 2144,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/plugins/remotely-save/styles.css",
    "existRemote": true,
    "mtimeRemote": 1651827766621,
    "mtimeRemoteFmt": "2022-05-06T18:02:46+09:00",
    "sizeRemoteEnc": 816,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/plugins/remotely-save/",
    "existRemote": true,
    "mtimeRemote": 1651827765395,
    "mtimeRemoteFmt": "2022-05-06T18:02:45+09:00",
    "sizeRemoteEnc": 0,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": "Stratus - Server/zzTemplate-Docker.md",
    "existRemote": true,
    "mtimeRemote": 1651830281951,
    "mtimeRemoteFmt": "2022-05-06T18:44:41+09:00",
    "sizeRemoteEnc": 624,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/hotkeys.json",
    "existRemote": true,
    "mtimeRemote": 1651827768461,
    "mtimeRemoteFmt": "2022-05-06T18:02:48+09:00",
    "sizeRemoteEnc": 32,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/plugins/homepage/main.js",
    "existRemote": true,
    "mtimeRemote": 1651827767843,
    "mtimeRemoteFmt": "2022-05-06T18:02:47+09:00",
    "sizeRemoteEnc": 73584,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/appearance.json",
    "existRemote": true,
    "mtimeRemote": 1651923665512,
    "mtimeRemoteFmt": "2022-05-07T20:41:05+09:00",
    "sizeRemoteEnc": 80,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/plugins/homepage/manifest.json",
    "existRemote": true,
    "mtimeRemote": 1651827767179,
    "mtimeRemoteFmt": "2022-05-06T18:02:47+09:00",
    "sizeRemoteEnc": 256,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/app.json",
    "existRemote": true,
    "mtimeRemote": 1651923665996,
    "mtimeRemoteFmt": "2022-05-07T20:41:05+09:00",
    "sizeRemoteEnc": 272,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false
  },
  {
    "key": ".obsidian/",
    "existRemote": true,
    "mtimeRemote": 1651827763475,
    "mtimeRemoteFmt": "2022-05-06T18:02:43+09:00",
    "sizeRemoteEnc": 0,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMappin
VM59:177 local: [
  {
    "key": ".obsidian/plugins/remotely-save/data.json",
    "existRemote": true,
    "mtimeRemote": 1651923695434,
    "mtimeRemoteFmt": "2022-05-07T20:41:35+09:00",
    "sizeRemoteEnc": 1904,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/plugins/obsidian-kanban/manifest.json",
    "existRemote": true,
    "mtimeRemote": 1651827766135,
    "mtimeRemoteFmt": "2022-05-06T18:02:46+09:00",
    "sizeRemoteEnc": 320,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": "Home.md",
    "existRemote": true,
    "mtimeRemote": 1651923316295,
    "mtimeRemoteFmt": "2022-05-07T20:35:16+09:00",
    "sizeRemoteEnc": 32,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/core-plugins.json",
    "existRemote": true,
    "mtimeRemote": 1651923665991,
    "mtimeRemoteFmt": "2022-05-07T20:41:05+09:00",
    "sizeRemoteEnc": 240,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/page-preview.json",
    "existRemote": true,
    "mtimeRemote": 1651830644390,
    "mtimeRemoteFmt": "2022-05-06T18:50:44+09:00",
    "sizeRemoteEnc": 48,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": "Stratus - Server/Traefik.md",
    "existRemote": true,
    "mtimeRemote": 1651831364591,
    "mtimeRemoteFmt": "2022-05-06T19:02:44+09:00",
    "sizeRemoteEnc": 2144,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/plugins/remotely-save/styles.css",
    "existRemote": true,
    "mtimeRemote": 1651827766621,
    "mtimeRemoteFmt": "2022-05-06T18:02:46+09:00",
    "sizeRemoteEnc": 816,
    "remoteEncryptedKey": "UREDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/plugins/remotely-save/",
    "existRemote": true,
    "mtimeRemote": 1651827765395,
    "mtimeRemoteFmt": "2022-05-06T18:02:45+09:00",
    "sizeRemoteEnc": 0,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": "Stratus - Server/zzTemplate-Docker.md",
    "existRemote": true,
    "mtimeRemote": 1651830281951,
    "mtimeRemoteFmt": "2022-05-06T18:44:41+09:00",
    "sizeRemoteEnc": 624,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/hotkeys.json",
    "existRemote": true,
    "mtimeRemote": 1651827768461,
    "mtimeRemoteFmt": "2022-05-06T18:02:48+09:00",
    "sizeRemoteEnc": 32,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/plugins/homepage/main.js",
    "existRemote": true,
    "mtimeRemote": 1651827767843,
    "mtimeRemoteFmt": "2022-05-06T18:02:47+09:00",
    "sizeRemoteEnc": 73584,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/appearance.json",
    "existRemote": true,
    "mtimeRemote": 1651923665512,
    "mtimeRemoteFmt": "2022-05-07T20:41:05+09:00",
    "sizeRemoteEnc": 80,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/plugins/homepage/manifest.json",
    "existRemote": true,
    "mtimeRemote": 1651827767179,
    "mtimeRemoteFmt": "2022-05-06T18:02:47+09:00",
    "sizeRemoteEnc": 256,
    "remoteEncryptedKey": "REDACTED",
    "changeRemoteMtimeUsingMapping": false,
    "existLocal": false
  },
  {
    "key": ".obsidian/app.json",
    "existRemote": true,
    "mtimeRemote": 1651923665996,
    "mtimeRemoteFmt": "2022-05-07T20:41:05+09:00",
    "sizeRemoteEnc": 272,
    "remoteEncryptedKey": "REDACTED",
VM59:177 localConfigDirContents: [
  {
    "key": ".obsidian/",
    "type": "folder",
    "ctime": null,
    "mtime": null
  },
  {
    "key": ".obsidian/plugins/",
    "type": "folder",
    "ctime": null,
    "mtime": null
  },
  {
    "key": ".obsidian/hotkeys.json",
    "type": "file",
    "ctime": 1651831501015,
    "mtime": 1651831501018,
    "size": 2
  },
  {
    "key": ".obsidian/core-plugins.json",
    "type": "file",
    "ctime": 1651831501545,
    "mtime": 1652005168153,
    "size": 222
  },
  {
    "key": ".obsidian/app.json",
    "type": "file",
    "ctime": 1651831502025,
    "mtime": 1652005167606,
    "size": 27
  },
  {
    "key": ".obsidian/appearance.json",
    "type": "file",
    "ctime": 1651831502038,
    "mtime": 1652005167620,
    "size": 24
  },
  {
    "key": ".obsidian/workspace",
    "type": "file",
    "ctime": 1651831502161,
    "mtime": 1652005545050,
    "size": 2155
  },
  {
    "key": ".obsidian/community-plugins.json",
    "type": "file",
    "ctime": 1651831784091,
    "mtime": 1652005168626,
    "size": 56
  },
  {
    "key": ".obsidian/plugins/obsidian-kanban/",
    "type": "folder",
    "ctime": null,
    "mtime": null
  },
  {
    "key": ".obsidian/plugins/remotely-save/",
    "type": "folder",
    "ctime": null,
    "mtime": null
  },
  {
    "key": ".obsidian/plugins/homepage/",
    "type": "folder",
    "ctime": null,
    "mtime": null
  },
  {
    "key": ".obsidian/plugins/obsidian-kanban/manifest.json",
    "type": "file",
    "ctime": 1651831779558,
    "mtime": 1651831779558,
    "size": 294
  },
  {
    "key": ".obsidian/plugins/obsidian-kanban/main.js",
    "type": "file",
    "ctime": 1651831780751,
    "mtime": 1651831780764,
    "size": 689285
  },
  {
    "key": ".obsidian/plugins/obsidian-kanban/styles.css",
    "type": "file",
    "ctime": 1651831781678,
    "mtime": 1651831781681,
    "size": 50889
  },
  {
    "key": ".obsidian/plugins/remotely-save/manifest.json",
    "type": "file",
    "ctime": 1651831794911,
    "mtime": 1651831794914,
    "size": 330
  },
  {
    "key": ".obsidian/plugins/remotely-save/main.js",
    "type": "file",
    "ctime": 1652004669296,
    "mtime": 1652004669376,
    "size": 2066057
  },
  {
    "key": ".obsidian/plugins/remotely-save/styles.css",
    "type": "file",
    "ctime": 1651831799771,
    "mtime": 1651831799774,
    "size": 799
  },
  {
    "key": ".obsidian/plugins/remotely-save/.gitignore",
    "type": "file",
    "ctime": 1651831817098,
    "mtime": 1651831817098,
    "size": 10
  },
  {
    "key": ".obsidian/plugins/remotely-save/data.json",
    "type": "file",
    "ctime": 1651831820374,
    "mtime": 1651896191232,
    "size": 1878
  },
  {
    "key": ".obsidian/plugins/homepage/manifest.json",
    "type": "file",
    "ctime": 1651831832784,
    "mtime": 1651831832788,
    "size": 232
  },
  {
    "key": ".obsidian/plugins/homepage/main.js",
    "type": "file",
    "ctime": 1651831833708,
    "mtime": 1651831833711,
    "size": 73558
  },
  {
    "key": ".obsidian/plugins/homepage/styles.css",
    "type": "file",
    "ctime": 1651831834118,
    "mtime": 1651831834121,
    "size": 9
  },
  {
    "key": ".obsidian/plugins/homepage/data.json",
    "type": "file",
    "ctime": 1651831835348,
    "mtime": 1651831835351,
    "size": 214
  }
]
VM59:177 remotely-save-1652007532308: abort sync, triggerSource=manual, error while generating_plan
eval @ VM59:177
eval @ VM59:216
s @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
eval @ VM59:177
a @ VM59:177
syncRun @ VM59:216
eval @ VM59:216
eval @ VM59:177
a @ VM59:177
eval @ VM59:216
VM59:177 Error: x=undefined is not a valid size
    at Me (eval at <anonymous> (app.js:1:1444808), <anonymous>:177:293719)
    at eval (eval at <anonymous> (app.js:1:1444808), <anonymous>:211:306916)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1444808), <anonymous>:177:280525)
    at new Promise (<anonymous>)
    at a (eval at <anonymous> (app.js:1:1444808), <anonymous>:177:280270)
    at eval (eval at <anonymous> (app.js:1:1444808), <anonymous>:211:305740)
    at eval (eval at <anonymous> (app.js:1:1444808), <anonymous>:211:308419)
    at Generator.next (<anonymous>)
    at eval (eval at <anonymous> (app.js:1:1444808), <anonymous>:177:280525)
eval @ VM59:177
eval @ VM59:216
s @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
a @ VM59:177
Promise.then (async)
u @ VM59:177
eval @ VM59:177
a @ VM59:177
syncRun @ VM59:216
eval @ VM59:216
eval @ VM59:177
a @ VM59:177
eval @ VM59:216
```

I have redacted the 'remoteEncryptedKey', just in case it could give any data that I shouldn't share.

To me (for my current skills), it doesn't help, but hopefully for you it would help.

PS: if you want the check console output page to more noob friendly, you can try to combine: https://developer.chrome.com/docs/devtools/remote-debugging/
and https://android.stackexchange.com/a/102184
It took me while to figure out I needed the phone in PTP and I had to do the `adb usb` (so install adb on my system) to be able to inspect the phone.

**Comment by UbioZur** [comment]
I FOUND IT! (While I was on it, and had some time to mess around).

Here is how I 'break' the sync, and here is how I get the sync:

- enable config sync: break (it does says experimental!)
- disable config sync: sync is working.


So here is the step by step of what I did on install (in case it is not a known bug).

- install Obisian on Fedora through FlatHub.
- select the plugins I want (homepage, template, kanban, remotely-save)
- do some Obsidian settings (Not many, I don't remember exactly)
- setup remotely-save (including config sync)
- Create some files and sync
- install Obsidian on Android
- install the same plugins
- setup remotely-save (including config sync)
- sync fail!
- Setup CORS
- sync fail
- disable config-sync
- sync successful
- enable config-sync
- sync fail
- ...

If you want to use my use case to try to debug / fix the config-sync issue (as it's experimental), I will leave that issue open.
If not (known bug for example), feel free to close the issue.

**Comment by fyears** [comment]
Hi,

1. I have hidden your full logs to prevent any unexpected sensitive info being posted public.
2. But, according to your found-outs about syncing config dir, and these lines inside your log:
    ```json
    {
        "key": ".obsidian/",
        "type": "folder",
        "ctime": null,
        "mtime": null
    },
    ```

    It seems that while reading the config dir `.obsidian` there was something wrong about reading the modified time `mtime` and creation time `ctime`.

    I will try to figure out what happen further. But before that I am afraid you have to turn off the config-sync setting.


Thank you so much for your detailed report!

**Comment by fyears** [comment]
And please do not forget to switch back to use the public release instead of the special debug release.

**Comment by fyears** [comment]
Fixed https://github.com/remotely-save/remotely-save/releases/tag/0.3.25
